language: generic
matrix:
  include:
    - script:
        - make test
        - pod lib lint
      env: JOB=Xcode
      os: osx
      osx_image: xcode8.2
      before_install:
        - pod repo update
    - script:
        - swift test
        - swiftlint
      env: JOB=SPM
      os: osx
      osx_image: xcode8.2
    - script: make docker_test
      env: JOB=Linux
      sudo: required
      services: docker
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
